### ISSUE TITLE
small NNUE weight in v5.0.0 ?

### ISSUE THREAD

**Issue by tissatussa** [Heiaha/Weiawaga#6]
[ this issue is related to issue #5 ]

I successfully compiled your new v5.0.0 !
In issue #5 you wrote that v4.0.0 was not a NNUE version .. but v5.0.0 is, so i wonder why my compiled binary is only 2.1 Mb, just like v4.0.0 .. the new v5.0.0 runs fine in CuteChess though.

NOTES :
I compiled (on Linux, Xubuntu 21.10) by `cargo build --release` , because i think that's the default method for Rust code .. you could mention this in the README. I often view such readme.md file in Okular, but then it does not display properly : the HTML-like codes are visible as-is .. to solve this, i discovered such readme.md file should have an empty first line !? (or is Okular buggy? I wonder..)

**Comment by Heiaha** [comment]
Hi, the network is relatively small because it only consists of a simple piece-square feature set instead of the more common (and larger) king-piece-square feature set, and it also is fully quantized.

**Comment by tissatussa** [comment]
Thank you for this reply. I'm not a chess engine programmer myself, but just user of engines - mostly with CuteChess. I think i know what an NN is and can do, from theoretical perspective, but in fact i have no clue .. piece-square tables i understand .. but piece-square tables compared to king-piece-square tables i'm unfamiliar with .. and what does "quantized" mean ?

Such PSTs are interesting though .. i like to communicate a bit more about this subject with you, but maybe in another "issue" ? Eg. i had some discussion with other chess engine programmers about KNN-vs-K : these endgames are always a draw, but many engines are unaware of it and thus may lose while winning ! Do your PST(s) regard that ?

**Comment by Heiaha** [comment]
Quantized in this case just means that all of the NN weights are integers. Nothing too fancy, but it does make the evaluation much faster.
